<a href="https://colab.research.google.com/github/kroupisgeo/PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Start to code

In [1]:
print('hello')

hello


In [2]:
import torch

In [3]:
torch.__version__

'2.10.0+cpu'

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cpu


In [5]:
!mps

/bin/bash: line 1: mps: command not found


### Creating tensors

We will go in order: Scalar, Vector, Matrix, Tensor

In [6]:
# scalar

scalar = torch.tensor(7)

In [7]:
scalar

tensor(7)

In [8]:
# number of dimensions
scalar.ndim

0

In [9]:
scalar.item() # get the tensor as Python int

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
# the dimensions of vector

vector.ndim

1

In [12]:
vector.shape # shape is the number of

torch.Size([2])

In [13]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [14]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim # we have two square brackets

2

In [16]:
MATRIX[1] # indexing

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2, 4, 5]]])

In [19]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [20]:
TENSOR.ndim # 3 square brackets pearings

3

In [21]:
TENSOR.shape # we have one (1), three by three tensor

torch.Size([1, 3, 3])

In [22]:
TENSOR[0] # what is the zero dimension

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
# my code for practice with tensor

T = torch.tensor([[[[[1,4,5],
                     [7,4,1],
                     [7,9,2]]]]])

In [24]:
T.ndim

5

In [25]:
T.shape

torch.Size([1, 1, 1, 3, 3])

### Randome Tensors

Why Random Tensors?

Random Tensors are important because they way many neural networks learn is that they start with tensors full of random numbers and then adjust these random numbers to better represent the data.

`Start with random numbers -> look at the data -> update the random numbers -> look at the data -> update the random number`

In [26]:
### Random Tensors of shape  (or size is the same), (3,4)

random_tensor = torch.rand(3,4)

In [27]:
random_tensor

tensor([[0.9389, 0.4227, 0.6856, 0.6875],
        [0.6571, 0.9771, 0.6017, 0.2023],
        [0.5644, 0.0343, 0.2657, 0.1457]])

In [28]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
random_tensor.ndim

2

In [30]:
# create a random sensor with similar shate of an image tensro

random_image_size_tensor = torch.rand(size=(3, 244,244)) # color channels, height, width

In [31]:
random_image_size_tensor.shape

torch.Size([3, 244, 244])

In [32]:
random_image_size_tensor.ndim

3

In [33]:
## Create my own random tensors

T1 = torch.rand(3,3,3)

In [34]:
T1

tensor([[[0.4636, 0.4082, 0.9287],
         [0.0129, 0.2157, 0.0471],
         [0.0066, 0.4668, 0.2662]],

        [[0.7028, 0.1630, 0.4453],
         [0.6579, 0.9717, 0.1786],
         [0.0979, 0.5136, 0.6891]],

        [[0.2544, 0.2283, 0.1563],
         [0.7483, 0.9568, 0.8430],
         [0.5374, 0.0015, 0.0019]]])

In [35]:
T1.ndim

3

In [36]:
T1[0]

tensor([[0.4636, 0.4082, 0.9287],
        [0.0129, 0.2157, 0.0471],
        [0.0066, 0.4668, 0.2662]])

In [37]:
T1.shape

torch.Size([3, 3, 3])

### Zeros and ones tensors

In [38]:
zeros = torch.zeros(size=(3,4))

In [39]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros * random_tensor # must be of the same size to allow multiplication

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
3 * random_tensor

tensor([[2.8166, 1.2681, 2.0568, 2.0626],
        [1.9713, 2.9314, 1.8051, 0.6069],
        [1.6931, 0.1029, 0.7970, 0.4371]])

In [42]:
ones = torch.ones(size=(3,4))

In [43]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
ones.dtype

torch.float32

In [45]:
ones * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
ones * random_tensor

tensor([[0.9389, 0.4227, 0.6856, 0.6875],
        [0.6571, 0.9771, 0.6017, 0.2023],
        [0.5644, 0.0343, 0.2657, 0.1457]])

### Create a range of tensors and tensors-like

In [47]:
torch.range(1,12,4) # start, stop, steps

/tmp/ipykernel_1755/3488388234.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,12,4) # start, stop, steps


tensor([1., 5., 9.])

In [48]:
torch.range(1,1000,77)

/tmp/ipykernel_1755/2093481672.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,1000,77)


tensor([  1.,  78., 155., 232., 309., 386., 463., 540., 617., 694., 771., 848.,
        925.])

In [49]:
one_to_ten = torch.range(1,11,1)

/tmp/ipykernel_1755/4086722979.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(1,11,1)


In [50]:
one_to_ten.shape

torch.Size([11])

In [51]:
# creating tensors-like
# will create a tensor based on the dimensions of another tensor

ten_zeros = torch.zeros_like(input=one_to_ten)

In [52]:
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
# create my own tensor-like

T1.shape

torch.Size([3, 3, 3])

In [54]:
my_zeroes = torch.zeros_like(input=T1)

In [55]:
my_zeroes

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [56]:
my_like = torch.rand_like(input=T1)

In [57]:
my_like

tensor([[[0.4103, 0.4676, 0.6517],
         [0.1492, 0.8396, 0.9537],
         [0.5497, 0.7416, 0.1733]],

        [[0.0562, 0.8428, 0.7969],
         [0.4628, 0.8983, 0.0819],
         [0.1268, 0.3369, 0.7516]],

        [[0.7536, 0.8779, 0.6800],
         [0.2122, 0.1400, 0.2748],
         [0.5472, 0.0248, 0.3492]]])

### Tensor Datatypes

Default datatype is float32

**NOTE:** Tensor datatypes is one of the 3 big errors with PyTorch and deep learning
1. Tensors are not right data type
2. Tensors are not right shape
3. Tensors not on the same device

In [58]:
float_32_tensor = torch.tensor([3., 6., 9]) # withour specifying the data type

In [59]:
float_32_tensor.dtype

torch.float32

In [60]:
float_32_tensor = torch.tensor([3.,6.,9.],
                               dtype = None, # no specific dtype
                               device = None, # no specific device to run, default is cpu
                               requires_grad = False) # to track the gradients of the tensor


In [61]:
float_32_tensor.dtype

torch.float32

In [62]:
float_32_tensor

tensor([3., 6., 9.])

In [63]:
float_32_tensor.device

device(type='cpu')

In [64]:
float_16_tensor = float_32_tensor.type(torch.float16) #conver the dtype of the tensor

In [65]:
float_16_tensor.dtype

torch.float16

In [66]:
# If I multiply tensor with different accuracy I suspect the the higher accuracy will be lost
# AND I WAS WRONG!!!! The higher accuracy will remain!!!!

mult_tensor = float_16_tensor * float_32_tensor

In [67]:
mult_tensor.dtype

torch.float32

In [68]:
# lets try the same between float and integer

int_64_tensor = torch.tensor([1,2,3])

In [69]:
int_64_tensor.dtype

torch.int64

In [70]:
mult_tensor2 = int_64_tensor * float_32_tensor

In [71]:
mult_tensor2.dtype

torch.float32

### Getting informations from Tensors (Tensor attributes)


1. data type
2. shape
3. the device

In [72]:
# Data type

mult_tensor.dtype

torch.float32

In [73]:
# Shape
mult_tensor.shape

torch.Size([3])

In [74]:
# device
mult_tensor.device

device(type='cpu')

In [75]:
# Create my own

my_tensor = torch.rand(size=(3,4),
                       dtype = torch.float64,
                       device = None)

In [76]:
my_tensor

tensor([[0.8121, 0.0796, 0.7675, 0.3401],
        [0.9490, 0.6277, 0.4805, 0.1609],
        [0.4306, 0.5848, 0.7681, 0.7991]], dtype=torch.float64)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [77]:
# Create a tensor

tensor = torch.tensor([1,2,4])

In [78]:
tensor

tensor([1, 2, 4])

In [79]:
tensor + 10

tensor([11, 12, 14])

In [80]:
tensor -1

tensor([0, 1, 3])

In [81]:
tensor -10

tensor([-9, -8, -6])

In [82]:
tensor * 10

tensor([10, 20, 40])

In [83]:
# in-built functions of PyTorch

torch.mul(tensor, 10)

tensor([10, 20, 40])

### Matrix Multiplication

Two main ways of performing mulitplication in neral netweokds and deep learning:

1. Element wise multiplication
2. Matrix multiplication (dot product)

In [84]:
# Element wise

tensor * tensor

tensor([ 1,  4, 16])

In [85]:
tensor

tensor([1, 2, 4])

In [86]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(21)

In [87]:
# Matrix multiplication by hand
1*1 + 2*2 + 4*4

21

In [88]:
tensor @ tensor

tensor(21)

In [89]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(21)
CPU times: user 352 µs, sys: 934 µs, total: 1.29 ms
Wall time: 1.55 ms


In [90]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 49 µs, sys: 0 ns, total: 49 µs
Wall time: 52 µs


tensor(21)

One of the most common errors in deep learing is **shape error**

There are two main rules that perfrorming matrix multiplication needs to satisfy:
1. the **inner space** must match
2. the resulting matrix has the shape of the **outer dimenstions**

In [91]:
# Example
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.8154, 1.1076, 0.2618],
        [0.4707, 0.5621, 0.0772],
        [0.9497, 1.2516, 0.2682]])

In [92]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [4,5],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])

In [93]:
tensor_A.shape

torch.Size([3, 2])

In [94]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

#### To fix tensor shape issues, we can manipulate the shape of one of our tensors using the **transpose matrix**

**Transpose** switches the axes or dimensions of a given tensor

In [95]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [96]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [97]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [98]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 78,  87,  96],
        [ 95, 106, 117]])

In [99]:
print(f"original tensor is {tensor_B}, and the transport is {tensor_B.T}")

original tensor is tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]), and the transport is tensor([[ 7,  8,  9],
        [10, 11, 12]])


### Tensor aggregation (find the min, max, mean, sum, etc)

In [100]:
# Create a tensor

x = torch.arange(0 , 100, 10)

In [101]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [102]:
torch.min(x)

tensor(0)

In [103]:
x.min()

tensor(0)

In [104]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [105]:
torch.mean(x) # will create an error. Error number 3, not the correct data type (here is Long)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [106]:
x.dtype

torch.int64

In [107]:
# see the documentation https://docs.pytorch.org/docs/2.11/generated/torch.mean.html$0
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [108]:
# similar code

torch.mean(x.type(torch.float32))

tensor(45.)

In [109]:
# another way of code
x.type(torch.float32).mean()

tensor(45.)

In [110]:
# find the sum

torch.sum(x)

tensor(450)

In [111]:
x.sum()

tensor(450)

### Find the positions of the min, max, etc

In [112]:
torch.argmin(x)

tensor(0)

In [113]:
torch.argmax(x)

tensor(9)

In [114]:
x.argmax()

tensor(9)

In [115]:
x.argmin()

tensor(0)

In [116]:
x[9]

tensor(90)

all the below are mine and make no much sense

In [117]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [118]:
tensor_B.argmax()

tensor(5)

In [119]:
tensor_B[2,1]

tensor(12)

In [120]:
tensor_B.max().index

<bound method Tensor.index of tensor(12)>

### Reshaping, stanking, squeezing, and unsqueezing tesnors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the the original tensor
* Stacing - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimenstions from a tensor
* Unsqueeze - add a `1` dimension to a tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [121]:
# create a tensor

x = torch.arange(1.,10.)

In [122]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

The tensor has 9 elements. That means that reshape will be possible if the new tensor will have 9 elements

In [126]:
# reshape with 7 elements will return an error

x_reshaped = x.reshape(1,7)

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [127]:
# reshpae with 18 elements will return an error

x_reshaped = x.reshape(2,9)

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [128]:
# the following reshape will work

x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.size

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 <function Tensor.size>)

In [129]:
# Change the view (And remember, view shares the same memory)

z = x.view(1,9)

In [130]:
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [131]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [132]:
z.shape

torch.Size([1, 9])

In [133]:
# Changing z changes x (because a view of tensor shares the same menory at the original tensor)

z[:,0] = 5

In [134]:
z ,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [135]:
# stach tensors on top of each other
# concatenates a sequence of tensors along an NEW dimension

x_stacked = torch.stack([x, x, x, x])

In [136]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [137]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [138]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

Squeeze

In [139]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [140]:
x_reshaped = x.reshape(1,9)

In [141]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [142]:
x_reshaped.squeeze() # will remove the one bracket.

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [143]:
x_reshaped.squeeze().shape

torch.Size([9])

In [144]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove an extra dimentions
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [145]:
# unsqueeze - adds a single dimension to a target tesnor at a specific dimension

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [146]:
# Add an extra dimension
print(f"\nNew tensor: {x_squeezed.unsqueeze(dim=1)}")
print(f"New shape : {x_squeezed.unsqueeze(dim=1).shape}")


New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape : torch.Size([9, 1])


In [147]:
# torch.permute - rearranges the dimenstions of a target tensor in a specific order

x_original = torch.rand(size=(224, 224 , 3)) # [height, width, colour_channel] tensor of an image


In [148]:
# Permute to put the colour first

x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1 , 1->2, 2->0

In [149]:
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing

In [150]:
x = torch.arange(1,10).reshape(1,3,3)

In [151]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [152]:
# index the first dimension tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [153]:
# index the first row of the first dimension (dim =1)
x[0][0]

tensor([1, 2, 3])

In [154]:
# index the most inner bracket (last dimension)

x[0][0][0]

tensor(1)

In [155]:
# all the values of the 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [156]:
# all the dimensions of the 0 dim but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [157]:
# get the index 0 of oth and 1st dimenstion and all valus of 2nd dimensions
x[0,0,:]

tensor([1, 2, 3])

In [158]:
x[0][2][2]

tensor(9)

In [159]:
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [160]:
import numpy as np

In [161]:
# NumPy array to tensor

array = np.arange(1., 8.)

In [162]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [163]:
tensor = torch.from_numpy(array)

In [166]:
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [165]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

**WARNING** when convertign np array to tensor the data type of the tensor will be the default of array i.e. float64

In [167]:
# Tenso to numpy

tensor = torch.ones(7)

In [168]:
numpy_tensor = tensor.numpy()

In [169]:
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [170]:
# change the tensor, what happend to the array? Nothing! not sharing memory

tensor = tensor +10

In [171]:
tensor, numpy_tensor

(tensor([11., 11., 11., 11., 11., 11., 11.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them representations of the data -> again -> again......`

To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.

In [174]:
# create two random tensors

rand_tensor_a = torch.rand(3,4)
rand_tensor_b = torch.rand(3,4)

print(rand_tensor_a)
print(rand_tensor_b)
print(rand_tensor_a == rand_tensor_b)

tensor([[0.0526, 0.0404, 0.4351, 0.0226],
        [0.8151, 0.3128, 0.8403, 0.8854],
        [0.1124, 0.9093, 0.7947, 0.9122]])
tensor([[0.7341, 0.9998, 0.3714, 0.9155],
        [0.4830, 0.7682, 0.4319, 0.9096],
        [0.7003, 0.3193, 0.9904, 0.9770]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [176]:
# random but reproducable tensors

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_tensor_d = torch.rand(3,4)

print(rand_tensor_c)
print(rand_tensor_d)
print(rand_tensor_c == rand_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor and PyTorch objects on the GPUs

1. the use the GPU of colab (go to Runtime and change)
2. use your own GPU
3. Use cloud computer

#### 1. Use the GPU of colab

In [2]:
!nvidia-smi

Fri May 15 07:02:43 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#### 2. Check for GPU access with PyTorch

In [3]:
## Check for GPU access with PyTorch

import torch

torch.cuda.is_available()

True

Check for Pytorch device agnostic code chwck the best practices at https://docs.pytorch.org/docs/2.12/notes/cuda.html$0

In [4]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"

In [5]:
device

'cuda'

In [6]:
# count the number of the devices

torch.cuda.device_count()

1

#### 3. Putting tensors (and models) on the GPU

In [8]:
# create a tensor (default on the CPU)

tensor = torch.tensor([1,2,3]) # even if we do not specify device = 'cpu'

print(tensor, tensor.device)



tensor([1, 2, 3]) cpu


In [9]:
# move tensot to gpu if availble

tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#### 4. Moving tensors back to the cpu

In [11]:
# if tensor is on GPPU, can't transform it ot NumPy

# the code will result to error
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [13]:
# to resolve, first set it to the CPU

tensor_back_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_cpu

array([1, 2, 3])

In [14]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [16]:
# we cannot make calculations on tensors located in different devices.
# The below will result on error

tensor_on_gpu + tensor_back_cpu

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.